### ISSUE TITLE
12-25 16:11:04 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_zyk_music, type=message, priority=0, temp=True> failed.

### ISSUE THREAD

**Issue by 16578** [ZYKsslm/nonebot_plugin_zyk_music#2]
File "C:\Users\16578\AppData\Local\pypoetry\Cache\virtualenvs\nonebot-uX-rUTH5-py3.9\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, 
in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='9', msg='FILE_SYSTEM_UPLOAD_API_ERROR', retcode=100, status='failed', 
wording='upload failed: upload failed: 96'>

**Comment by 16578** [comment]
有的歌下载成功，但是发不出来，报出这样的错误。有些歌是可以发出来的

**Comment by ZYKsslm** [comment]
你确定在同一个群中有的发得出来，有的报错？这是上传群文件或私聊文件失败，你看看是不是QQ的问题

**Comment by 16578** [comment]
是一个群，有的发的了，有的不行，QQ用的最新的go-cq，nonebot应该也是最新的

**Comment by 16578** [comment]
我用的chatgpt插件设置的fastapi是false，跟这个有关系吗

**Comment by 16578** [comment]
[2022-12-25 16:11:04] [WARNING]: 上传群 698063561 文件 D:\Users\16578\PycharmProjects\bot\data\cache\93dc698c365c709f25a66a7d8c05edd6.cache 失败: upload 
failed: upload failed: 96
gocq显示的这个，这是不是gocq有问题呀

**Comment by ZYKsslm** [comment]
应该不是，我想起来了，这好像是gocq的一个BUG，你试试进到源码里找到最后一行上传文件的代码把name参数删掉
![image](https://user-images.githubusercontent.com/110616928/209461872-de79e13e-b5bb-4a5d-9993-7e60a71dd6a7.png)

**Comment by ZYKsslm** [comment]
应该不是，这个问题先放着吧

**Comment by 16578** [comment]
好嘞好嘞

**Comment by ZYKsslm** [comment]
代码重写了，应该没有问题了
