### ISSUE TITLE
json文件貌似有问题？无法正常使用

### ISSUE THREAD

**Issue by enderadmin** [ZYKsslm/nonebot_plugin_zyk_music#9]
![Screenshot_2023-08-05-19-21-39-10](https://github.com/ZYKsslm/nonebot_plugin_zyk_music/assets/113816011/0b09fec6-f253-4f12-8ea5-ba8bbdc41091)

**Comment by ZYKsslm** [comment]
> ![Screenshot_2023-08-05-19-21-39-10](https://github.com/ZYKsslm/nonebot_plugin_zyk_music/assets/113816011/0b09fec6-f253-4f12-8ea5-ba8bbdc41091)
> 

由于接口跑路，这个项目暂时废了，我会尽快解决，现在先暂停维护。
